### ISSUE TITLE
Epic: Improve Pre-Aggregations Developer Experience

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#2546]
Improve developer experience with pre-aggregations and provide more tools to debug and inspect pre-aggregations. 

Some of the issues we'll work on as part of this epic are.

- [x] Improve data schema API for defining and managing pre-aggregations
- [ ] Add tools to Playground to inspect queries and pre-aggregations
- [x] Improve configuration to streamline the deployment process for pre-aggregations
- [x] Add documentation to run and scale Cube Store in production
