### ISSUE TITLE
Epic: Improve refresh worker for pre-aggregations

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#3105]
Improve refresh worker to speed up the pre-aggregations build process. 

Some of the work items include: 

- [ ] Split refresh worker into two processes.
- [ ] Introduce per-DB-type defaults for refresh worker concurrency and pre-aggregation queue concurrency. 
- [x] Rolling window support for pre-aggregation.

**Comment by rpaik** [comment]
Splitting refresh worker is mostly not relevant for Cube.js.
