### ISSUE TITLE
Epic: Improve the user experience for big datasets

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#3107]
Make additional investments to improve the user experience for big datasets such as Big Query, Redshift, Snowflake, etc. 

Some of the work items include: 

- [x] Prioritize features/bug fixes that are needed for big datasets.
- [x] Improve support for BigQuery/RedShift/Snowflake drivers. 
- [x] [Cast all numerical values as strings](https://github.com/cube-js/cube.js/issues/1879).
